
FROM node:20-bookworm-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm i


FROM deps AS prod-builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build


FROM prod-builder AS production
COPY --from=prod-builder /app/dist .
RUN npm install -g serve
ENV PORT=5173
EXPOSE 5173
CMD ["serve","-s","dist"]

# 